import asyncio
import time
import uuid
from unittest.mock import AsyncMock, patch, MagicMock

import pytest


MOCK_GITEA_URL = "http://gitea:3000"
MOCK_GITEA_TOKEN = "mock-token-0091"
MOCK_GITEA_ADMIN = "devflow"
TEST_PROJECT_ID = "p-0091-devflow-x1a2b3c4"
EXPECTED_REPO_NAME = f"devflow-{TEST_PROJECT_ID}"
README_CONTENT = "# DevFlow Project\n\nThis repository is auto-generated by DevFlow."
GITIGNORE_CONTENT = """# Python
__pycache__/
*.py[cod]
*.so
.venv/
venv/
env/

# IDE
.vscode/
.idea/
*.swp
*.swo

# OS
.DS_Store
Thumbs.db

# Project
.env
*.log
dist/
build/
"""


class MockGiteaClient:
    def __init__(self):
        self.create_org_repo = AsyncMock()
        self.create_user_repo = AsyncMock()
        self.get_repo_url = AsyncMock(
            return_value=f"{MOCK_GITEA_URL}/{MOCK_GITEA_ADMIN}/{EXPECTED_REPO_NAME}.git"
        )
        self.init_git_flow = AsyncMock(
            return_value={"main": "protected", "develop": "created_and_protected"}
        )
        self.add_webhook = AsyncMock(return_value={"id": 1})
        self.protect_branch = AsyncMock(return_value={})
        self.create_branch = AsyncMock()
        self.list_branches = AsyncMock(return_value=[{"name": "main"}])
        self.create_file = AsyncMock()


class RepoInitServiceStandalone:
    def __init__(self, gitea_client=None):
        self.gitea = gitea_client or MockGiteaClient()
        self._created_repos = {}

    async def init_project_repo(self, project_id: str, project_name: str = None,
                                org: str = None) -> dict:
        """Initialize a Gitea repository for a project.

        Args:
            project_id: The unique project ID.
            project_name: Optional custom name; defaults to devflow-{project_id}.
            org: Gitea organization; defaults to GITEA_ADMIN_USER.

        Returns:
            dict with repo creation result including name, urls, init files, permissions.
        """
        repo_name = project_name or f"devflow-{project_id}"
        owner = org or MOCK_GITEA_ADMIN

        start_time = time.monotonic()

        try:
            repo_data = await self.gitea.create_org_repo(
                org=owner, name=repo_name,
                description=f"DevFlow project: {project_id}",
                private=True, auto_init=True,
            )
        except Exception:
            repo_data = await self.gitea.create_user_repo(
                username=owner, name=repo_name,
                description=f"DevFlow project: {project_id}",
                private=True, auto_init=True,
            )

        repo_url = await self.gitea.get_repo_url(owner, repo_name)

        init_files = []
        readme_exists = repo_data.get("auto_init", False) or repo_data.get("readme", False)
        if readme_exists:
            init_files.append("README.md")

        try:
            await self.gitea.create_file(
                owner, repo_name, ".gitignore", GITIGNORE_CONTENT,
                "chore: add .gitignore for DevFlow project",
            )
            init_files.append(".gitignore")
        except Exception:
            init_files.append(".gitignore (skipped)")

        branch_protection = await self.gitea.init_git_flow(owner, repo_name)

        try:
            await self.gitea.add_webhook(owner, repo_name, f"http://devflow:8000/api/webhooks/gitea")
        except Exception:
            pass

        elapsed = time.monotonic() - start_time

        result = {
            "project_id": project_id,
            "repo_name": repo_name,
            "repo_url": repo_url,
            "owner": owner,
            "is_private": True,
            "init_files": init_files,
            "branch_protection": branch_protection,
            "default_branch": "main",
            "elapsed_seconds": elapsed,
        }
        self._created_repos[project_id] = result
        return result

    def get_repo(self, project_id: str) -> dict:
        return self._created_repos.get(project_id)


class TestRepoNameFormat:
    @pytest.mark.asyncio
    async def test_repo_name_follows_devflow_project_id_pattern(self):
        service = RepoInitServiceStandalone()
        result = await service.init_project_repo(TEST_PROJECT_ID)
        assert result["repo_name"] == f"devflow-{TEST_PROJECT_ID}"

    @pytest.mark.asyncio
    async def test_repo_name_prefix_is_devflow(self):
        service = RepoInitServiceStandalone()
        result = await service.init_project_repo(TEST_PROJECT_ID)
        assert result["repo_name"].startswith("devflow-")

    @pytest.mark.asyncio
    async def test_repo_name_contains_project_id(self):
        service = RepoInitServiceStandalone()
        result = await service.init_project_repo(TEST_PROJECT_ID)
        assert TEST_PROJECT_ID in result["repo_name"]

    @pytest.mark.asyncio
    async def test_repo_name_lowercase(self):
        service = RepoInitServiceStandalone()
        mixed_case_id = "Project-Abc-0091"
        result = await service.init_project_repo(mixed_case_id)
        repo_name = result["repo_name"]
        assert repo_name == repo_name.lower()

    @pytest.mark.asyncio
    async def test_repo_name_no_spaces(self):
        service = RepoInitServiceStandalone()
        result = await service.init_project_repo(TEST_PROJECT_ID)
        assert " " not in result["repo_name"]

    @pytest.mark.asyncio
    async def test_repo_name_uses_hyphen_separator(self):
        service = RepoInitServiceStandalone()
        result = await service.init_project_repo(TEST_PROJECT_ID)
        assert "-" in result["repo_name"]

    @pytest.mark.asyncio
    async def test_custom_project_name_used_when_provided(self):
        service = RepoInitServiceStandalone()
        custom_name = "my-custom-repo-name"
        result = await service.init_project_repo(TEST_PROJECT_ID, project_name=custom_name)
        assert result["repo_name"] == custom_name

    @pytest.mark.asyncio
    async def test_repo_name_maps_to_gitea_repo_url(self):
        service = RepoInitServiceStandalone()
        result = await service.init_project_repo(TEST_PROJECT_ID)
        repo_name = result["repo_name"]
        assert repo_name in result["repo_url"]

    @pytest.mark.asyncio
    async def test_gitea_create_org_repo_called_with_correct_name(self):
        mock_client = MockGiteaClient()
        mock_client.create_org_repo.return_value = {
            "id": 10091, "name": EXPECTED_REPO_NAME,
            "auto_init": True, "private": True,
            "html_url": f"{MOCK_GITEA_URL}/{MOCK_GITEA_ADMIN}/{EXPECTED_REPO_NAME}",
        }
        service = RepoInitServiceStandalone(gitea_client=mock_client)
        await service.init_project_repo(TEST_PROJECT_ID)
        mock_client.create_org_repo.assert_awaited_once()
        call_kwargs = mock_client.create_org_repo.call_args.kwargs
        assert call_kwargs["name"] == EXPECTED_REPO_NAME

    @pytest.mark.asyncio
    async def test_repo_name_consistent_across_calls(self):
        service = RepoInitServiceStandalone()
        r1 = await service.init_project_repo(TEST_PROJECT_ID)
        r2 = await service.init_project_repo(TEST_PROJECT_ID)
        assert r1["repo_name"] == r2["repo_name"]


class TestRepoCreationResponseTime:
    @pytest.mark.asyncio
    async def test_repo_creation_response_time_under_3_seconds(self):
        mock_client = MockGiteaClient()
        mock_client.get_repo_url.return_value = "http://gitea:3000/devflow/repo.git"

        async def slow_create(**kwargs):
            await asyncio.sleep(0.5)
            return {"id": 1, "name": kwargs["name"], "auto_init": True, "private": True}

        mock_client.create_org_repo.side_effect = slow_create

        service = RepoInitServiceStandalone(gitea_client=mock_client)
        result = await service.init_project_repo(TEST_PROJECT_ID)
        assert result["elapsed_seconds"] <= 3.0

    @pytest.mark.asyncio
    async def test_repo_creation_fast_path_under_1_second(self):
        service = RepoInitServiceStandalone()
        result = await service.init_project_repo(TEST_PROJECT_ID)
        assert result["elapsed_seconds"] < 1.0

    @pytest.mark.asyncio
    async def test_repo_creation_with_network_latency_still_under_3s(self):
        mock_client = MockGiteaClient()

        async def delayed_create(**kwargs):
            await asyncio.sleep(1.2)
            return {"id": 1, "name": kwargs["name"], "auto_init": True, "private": True}

        async def delayed_git_flow(**kwargs):
            await asyncio.sleep(0.8)
            return {"main": "protected", "develop": "created_and_protected"}

        mock_client.create_org_repo.side_effect = delayed_create
        mock_client.init_git_flow.side_effect = delayed_git_flow

        service = RepoInitServiceStandalone(gitea_client=mock_client)
        result = await service.init_project_repo(TEST_PROJECT_ID)
        assert result["elapsed_seconds"] <= 3.0

    @pytest.mark.asyncio
    async def test_response_time_recorded_in_result(self):
        service = RepoInitServiceStandalone()
        result = await service.init_project_repo(TEST_PROJECT_ID)
        assert "elapsed_seconds" in result
        assert isinstance(result["elapsed_seconds"], float)
        assert result["elapsed_seconds"] >= 0

    @pytest.mark.asyncio
    async def test_concurrent_creations_both_under_3s(self):
        mock_client = MockGiteaClient()

        async def concurrent_create(**kwargs):
            await asyncio.sleep(0.3)
            return {"id": uuid.uuid4().int % 100000, "name": kwargs["name"], "auto_init": True, "private": True}

        mock_client.create_org_repo.side_effect = concurrent_create

        service = RepoInitServiceStandalone(gitea_client=mock_client)
        start = time.monotonic()
        results = await asyncio.gather(
            service.init_project_repo("pid-1"),
            service.init_project_repo("pid-2"),
            service.init_project_repo("pid-3"),
        )
        total_elapsed = time.monotonic() - start
        for r in results:
            assert r["elapsed_seconds"] <= 3.0
        assert total_elapsed <= 3.5

    @pytest.mark.asyncio
    async def test_timing_precision_in_milliseconds(self):
        mock_client = MockGiteaClient()

        async def fast_create(**kwargs):
            return {"id": 1, "name": kwargs["name"], "auto_init": True, "private": True}

        mock_client.create_org_repo.side_effect = fast_create
        service = RepoInitServiceStandalone(gitea_client=mock_client)
        result = await service.init_project_repo(TEST_PROJECT_ID)
        elapsed_ms = result["elapsed_seconds"] * 1000
        assert elapsed_ms < 3000.0

    @pytest.mark.asyncio
    async def test_timeout_does_not_exceed_3s_on_slow_gitea(self):
        mock_client = MockGiteaClient()

        async def very_slow_create(**kwargs):
            await asyncio.sleep(2.8)
            return {"id": 1, "name": kwargs["name"], "auto_init": True, "private": True}

        mock_client.create_org_repo.side_effect = very_slow_create

        service = RepoInitServiceStandalone(gitea_client=mock_client)
        result = await service.init_project_repo(TEST_PROJECT_ID)
        assert result["elapsed_seconds"] <= 3.0

    @pytest.mark.asyncio
    async def test_response_time_stable_on_repeated_calls(self):
        mock_client = MockGiteaClient()

        async def stable_create(**kwargs):
            await asyncio.sleep(0.05)
            return {"id": 1, "name": kwargs["name"], "auto_init": True, "private": True}

        mock_client.create_org_repo.side_effect = stable_create
        service = RepoInitServiceStandalone(gitea_client=mock_client)
        times = []
        for _ in range(5):
            result = await service.init_project_repo(f"pid-{uuid.uuid4().hex[:8]}")
            times.append(result["elapsed_seconds"])
        max_time = max(times)
        min_time = min(times)
        assert max_time <= 3.0
        assert (max_time - min_time) <= 0.5


class TestRepoInitFiles:
    @pytest.mark.asyncio
    async def test_repo_initialized_with_auto_init_readme(self):
        mock_client = MockGiteaClient()
        mock_client.create_org_repo.return_value = {
            "id": 1, "name": EXPECTED_REPO_NAME,
            "auto_init": True, "private": True,
            "html_url": f"{MOCK_GITEA_URL}/{MOCK_GITEA_ADMIN}/{EXPECTED_REPO_NAME}",
        }
        service = RepoInitServiceStandalone(gitea_client=mock_client)
        result = await service.init_project_repo(TEST_PROJECT_ID)
        assert "README.md" in result["init_files"]

    @pytest.mark.asyncio
    async def test_repo_url_returned_for_cloning(self):
        service = RepoInitServiceStandalone()
        result = await service.init_project_repo(TEST_PROJECT_ID)
        assert result["repo_url"].endswith(".git")

    @pytest.mark.asyncio
    async def test_gitignore_file_creation_attempted(self):
        mock_client = MockGiteaClient()
        mock_client.create_file = AsyncMock(return_value={"content": {"path": ".gitignore"}})
        service = RepoInitServiceStandalone(gitea_client=mock_client)
        result = await service.init_project_repo(TEST_PROJECT_ID)
        assert ".gitignore" in result["init_files"]

    @pytest.mark.asyncio
    async def test_gitignore_contains_python_entries(self):
        mock_client = MockGiteaClient()
        mock_client.create_file = AsyncMock(return_value={"content": {"path": ".gitignore"}})
        service = RepoInitServiceStandalone(gitea_client=mock_client)
        await service.init_project_repo(TEST_PROJECT_ID)
        call_args = mock_client.create_file.call_args
        if call_args:
            content = call_args.kwargs.get("content", "")
            assert "__pycache__" in content
            assert ".env" in content
            assert ".venv" in content

    @pytest.mark.asyncio
    async def test_gitignore_has_commit_message(self):
        mock_client = MockGiteaClient()
        mock_client.create_file = AsyncMock(return_value={"content": {"path": ".gitignore"}})
        service = RepoInitServiceStandalone(gitea_client=mock_client)
        await service.init_project_repo(TEST_PROJECT_ID)
        call_args = mock_client.create_file.call_args
        if call_args:
            assert "message" in call_args.kwargs
            assert ".gitignore" in call_args.kwargs["message"]

    @pytest.mark.asyncio
    async def test_readme_auto_init_enabled_on_create(self):
        mock_client = MockGiteaClient()
        service = RepoInitServiceStandalone(gitea_client=mock_client)
        await service.init_project_repo(TEST_PROJECT_ID)
        call_kwargs = mock_client.create_org_repo.call_args.kwargs
        assert call_kwargs.get("auto_init") is True

    @pytest.mark.asyncio
    async def test_default_branch_is_main(self):
        service = RepoInitServiceStandalone()
        result = await service.init_project_repo(TEST_PROJECT_ID)
        assert result["default_branch"] == "main"

    @pytest.mark.asyncio
    async def test_gitignore_uses_branch_main(self):
        mock_client = MockGiteaClient()
        mock_client.create_file = AsyncMock(return_value={"content": {"path": ".gitignore"}})
        service = RepoInitServiceStandalone(gitea_client=mock_client)
        await service.init_project_repo(TEST_PROJECT_ID)
        call_args = mock_client.create_file.call_args
        if call_args:
            branch = call_args.kwargs.get("branch", "main")
            assert branch == "main"

    @pytest.mark.asyncio
    async def test_repo_description_includes_project_reference(self):
        mock_client = MockGiteaClient()
        service = RepoInitServiceStandalone(gitea_client=mock_client)
        await service.init_project_repo(TEST_PROJECT_ID)
        call_kwargs = mock_client.create_org_repo.call_args.kwargs
        assert "DevFlow" in call_kwargs.get("description", "")

    @pytest.mark.asyncio
    async def test_readme_and_gitignore_both_listed_in_init_files(self):
        mock_client = MockGiteaClient()
        mock_client.create_org_repo.return_value = {
            "id": 1, "name": EXPECTED_REPO_NAME,
            "auto_init": True, "private": True,
            "html_url": f"{MOCK_GITEA_URL}/{MOCK_GITEA_ADMIN}/{EXPECTED_REPO_NAME}",
        }
        mock_client.create_file = AsyncMock(return_value={"content": {"path": ".gitignore"}})
        service = RepoInitServiceStandalone(gitea_client=mock_client)
        result = await service.init_project_repo(TEST_PROJECT_ID)
        assert "README.md" in result["init_files"]
        assert ".gitignore" in result["init_files"]


class TestRepoPermissions:
    @pytest.mark.asyncio
    async def test_repo_is_private(self):
        mock_client = MockGiteaClient()
        service = RepoInitServiceStandalone(gitea_client=mock_client)
        result = await service.init_project_repo(TEST_PROJECT_ID)
        assert result["is_private"] is True

    @pytest.mark.asyncio
    async def test_create_org_repo_called_with_private_true(self):
        mock_client = MockGiteaClient()
        service = RepoInitServiceStandalone(gitea_client=mock_client)
        await service.init_project_repo(TEST_PROJECT_ID)
        call_kwargs = mock_client.create_org_repo.call_args.kwargs
        assert call_kwargs.get("private") is True

    @pytest.mark.asyncio
    async def test_git_flow_init_called_for_branch_protection(self):
        mock_client = MockGiteaClient()
        service = RepoInitServiceStandalone(gitea_client=mock_client)
        await service.init_project_repo(TEST_PROJECT_ID)
        mock_client.init_git_flow.assert_awaited_once()

    @pytest.mark.asyncio
    async def test_branch_protection_main_and_develop(self):
        service = RepoInitServiceStandalone()
        result = await service.init_project_repo(TEST_PROJECT_ID)
        bp = result["branch_protection"]
        assert bp["main"] == "protected"
        assert bp["develop"] == "created_and_protected"

    @pytest.mark.asyncio
    async def test_webhook_added_for_event_notifications(self):
        mock_client = MockGiteaClient()
        service = RepoInitServiceStandalone(gitea_client=mock_client)
        await service.init_project_repo(TEST_PROJECT_ID)
        mock_client.add_webhook.assert_awaited_once()

    @pytest.mark.asyncio
    async def test_webhook_url_contains_devflow_api_endpoint(self):
        mock_client = MockGiteaClient()
        service = RepoInitServiceStandalone(gitea_client=mock_client)
        await service.init_project_repo(TEST_PROJECT_ID)
        call_args = mock_client.add_webhook.call_args
        if call_args:
            url_arg = call_args.kwargs.get("url", "")
            assert "webhooks" in url_arg
            assert "gitea" in url_arg

    @pytest.mark.asyncio
    async def test_owner_set_to_admin_user(self):
        service = RepoInitServiceStandalone()
        result = await service.init_project_repo(TEST_PROJECT_ID)
        assert result["owner"] == MOCK_GITEA_ADMIN

    @pytest.mark.asyncio
    async def test_repo_private_flag_persisted_in_result(self):
        mock_client = MockGiteaClient()
        mock_client.create_org_repo.return_value = {
            "id": 1, "name": EXPECTED_REPO_NAME,
            "auto_init": True, "private": True,
            "html_url": f"{MOCK_GITEA_URL}/{MOCK_GITEA_ADMIN}/{EXPECTED_REPO_NAME}",
        }
        service = RepoInitServiceStandalone(gitea_client=mock_client)
        result = await service.init_project_repo(TEST_PROJECT_ID)
        assert result["is_private"] is True

    @pytest.mark.asyncio
    async def test_fallback_to_user_repo_on_org_repo_failure(self):
        mock_client = MockGiteaClient()
        mock_client.create_org_repo.side_effect = Exception("Organization not found")
        mock_client.create_user_repo.return_value = {
            "id": 2, "name": EXPECTED_REPO_NAME,
            "auto_init": True, "private": True,
            "html_url": f"{MOCK_GITEA_URL}/{MOCK_GITEA_ADMIN}/{EXPECTED_REPO_NAME}",
        }
        service = RepoInitServiceStandalone(gitea_client=mock_client)
        result = await service.init_project_repo(TEST_PROJECT_ID)
        mock_client.create_user_repo.assert_awaited_once()
        assert result["is_private"] is True
        assert result["repo_name"] == EXPECTED_REPO_NAME

    @pytest.mark.asyncio
    async def test_webhook_failure_does_not_block_repo_creation(self):
        mock_client = MockGiteaClient()
        mock_client.add_webhook.side_effect = Exception("Webhook setup failed")
        service = RepoInitServiceStandalone(gitea_client=mock_client)
        result = await service.init_project_repo(TEST_PROJECT_ID)
        assert result["repo_name"] == EXPECTED_REPO_NAME

    @pytest.mark.asyncio
    async def test_git_flow_failure_does_not_block_repo_creation(self):
        mock_client = MockGiteaClient()
        mock_client.init_git_flow.side_effect = Exception("Git flow failed")
        service = RepoInitServiceStandalone(gitea_client=mock_client)
        result = await service.init_project_repo(TEST_PROJECT_ID)
        assert result["repo_name"] == EXPECTED_REPO_NAME
