FROM node:20-alpine as builder

WORKDIR /app

COPY package.json package-lock.json* ./

RUN npm install --legacy-peer-deps

COPY . .

RUN VITE_API_BASE_URL=/api VITE_WS_BASE_URL=ws://localhost:9000 npm run build

FROM alpine:3.19

WORKDIR /app

COPY --from=builder /app/dist ./dist

CMD ["sh", "-c", "cp -r /app/dist/. /output/"]
