export { apiClient } from './client'

export { authApi } from './modules/auth'
export { boardApi } from './modules/board'
export { taskApi, commentApi, attachmentApi, dependencyApi } from './modules/task'
export { workloadApi } from './modules/workload'
export { inboxApi } from './modules/inbox'
export { userApi } from './modules/user'
export { requirementApi } from './modules/requirement'
export { projectSrsApi } from './modules/project'
